spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:productDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: true
  jackson:
    default-property-inclusion: "NON_NULL"
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: "always"

feature:
  toggle:
    offers-enabled: true

integration:
  offers:
    base-url: http://localhost:9999/offers?type={0}