platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: sample-spring-cache-app

outputs:
  - name: build-output

#run:
#  path: "sample-spring-cache-app/ci/scripts/build.sh"

run:
  path: echo
  args:
    - 'Executing Build'
