node {
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git('https://github.com/kkester/sample-spring-cache.git')
    }
    stage('Build') {
        // Run the maven build
        sh('./mvnw clean package')
    }
    stage('Results') {
        junit '**/build/test-results/test/TEST-*.xml'
        archiveArtifacts('target/*.jar')
    }
    stage("Deploy") {
        sh('cf push')
    }
    stage("Integration Test") {
        sh('./mvnw verify -Dunit.tests.skip=true')
    }
}