node {
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git('https://github.com/kkester/sample-spring-cache.git')
    }
    stage('Build') {
        // Run the maven build
        sh('./mvnw clean package')
    }
    stage('Results') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archiveArtifacts('target/*.jar')
    }
    stage("Deploy") {
        sh('cf push')
    }
    stage("Integration Test") {
        sh("./mvnw verify -Dunit.tests.skip=true -Dcache_app_url=${APP_URL}")
    }
}