---
resources:
  - name: sample-spring-cache-app
    type: git
    source:
      uri: https://github.com/kkester/sample-spring-cache.git
      branch: master
    check_every: 30s

jobs:
  - name: build
    public: true
    plan:
      - get: sample-spring-cache-app
        trigger: true
      - task: Build project
        file: sample-spring-cache-app/ci/tasks/build.yml
      - task: Deploy App
        file: sample-spring-cache-app/ci/tasks/deploy.yml
      - task: Execute Integration Tests
        file: sample-spring-cache-app/ci/tasks/integration-test.yml
